export const watchPartyConfig = {
    firebase: {
        apiKey: "YOUR_FIREBASE_WEB_API_KEY",
        authDomain: "YOUR_PROJECT.firebaseapp.com",
        databaseURL: "https://YOUR_PROJECT-default-rtdb.firebaseio.com",
        projectId: "YOUR_PROJECT",
        appId: "YOUR_FIREBASE_WEB_APP_ID"
    },
    useEmulators: false,
    emulators: {
        auth: { url: "http://127.0.0.1:9099" },
        database: { host: "127.0.0.1", port: 9000 },
        ui: { url: "http://127.0.0.1:4000" }
    },
    rtcConfig: {
        iceServers: [
            { urls: "stun:stun.l.google.com:19302" },
            { urls: "stun:stun1.l.google.com:19302" }
        ]
    },
    rtc: {
        iceServers: [
            { urls: "stun:stun.l.google.com:19302" },
            { urls: "stun:stun1.l.google.com:19302" }
        ],
        turnCredentialsEndpoint: "",
        connectionTimeoutMs: 10000,
        maxIceRestarts: 2,
        relayFallback: true
    },
    optionalTurn: {
        enabled: false,
        note: "Use short-lived TURN credentials generated by your own backend or TURN provider.",
        iceServers: []
    },
    roomLifetimeMs: 6 * 60 * 60 * 1000,
    serviceCheckTimeoutMs: 4000,
    createRoomTimeoutMs: 10000,
    joinRoomTimeoutMs: 10000,
    replaceMediaTimeoutMs: 10000,
    nativeMetadataTimeoutMs: 15000,
    restoreTimeoutMs: 10000,
    maxStoredSessionAgeMs: 6 * 60 * 60 * 1000,
    subtitleSizeLimit: 300 * 1024,
    chatLengthLimit: 500,
    maxChatMessages: 75,
    mediabunny: {
        moduleUrl: "https://esm.sh/mediabunny@1.52.3",
        ac3ModuleUrl: "https://esm.sh/@mediabunny/ac3@1.52.3"
    },
    sync: {
        heartbeatMs: 5000,
        smallDriftMs: 250,
        hardSeekDriftMs: 1000,
        softCorrectionRateDelta: 0.06,
        bufferDebounceMs: 1200
    }
};
